"""sig-rust: Fast path signature computation in Rust with Python bindings."""

from sig_rust._lib import (
    PreparedData,
    RotInv2DPreparedData,
    basis,
    logsig,
    logsig_expanded,
    logsigbackprop,
    logsiglength,
    prepare,
    rotinv2d,
    rotinv2dcoeffs,
    rotinv2dlength,
    rotinv2dprepare,
    sig,
    sigbackprop,
    sigcombine,
    sigjacobian,
    sigjoin,
    sigjoinbackprop,
    siglength,
    sigscale,
    sigscalebackprop,
    version,
)

__version__ = version()

__all__ = [
    "PreparedData",
    "RotInv2DPreparedData",
    "__version__",
    "basis",
    "logsig",
    "logsig_expanded",
    "logsigbackprop",
    "logsiglength",
    "prepare",
    "rotinv2d",
    "rotinv2dcoeffs",
    "rotinv2dlength",
    "rotinv2dprepare",
    "sig",
    "sigbackprop",
    "sigcombine",
    "sigjacobian",
    "sigjoin",
    "sigjoinbackprop",
    "siglength",
    "sigscale",
    "sigscalebackprop",
    "version",
]
